# Generated by Django 2.0.13 on 2020-09-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('wdate', models.DateTimeField()),
                ('writer', models.CharField(max_length=50)),
                ('hit', models.IntegerField()),
            ],
        ),
    ]
